Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -296,45 +296,61 @@ jobs:
                             cd .circleci/ansible
                             echo "Contents  of the inventory.txt file is -------"
                             cat inventory.txt
-                            ansible-playbook -i inventory.txt deploy-backend.yml -v
-        #    - run:
-        #       name: Install dependencies
-        #       command: |
-        #         sudo apt-get install zip unzip python ansible python-pip && pip install awscli
-        #    - run:
-        #        name: Deploy backend
-        #        command: |
-        #         cd backend
-        #         npm i
-        #         npm run build
-        #         cd ..
-        #         tar -C backend -cf artifact.tar .
-        #         ls -lrth artifact.tar
-        #         mv artifact.tar ~/project/.circleci/ansible/roles/deploy/files
-        #    - run:
-        #         name: Deploy backend ansible
-        #         command: |           
-        #             cd .circleci/ansible
-        #             echo "Contents  of the inventory.txt file is -------"
-        #             cat inventory.txt 
-        #             ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.txt deploy-backend.yml -vv
-        #    - run:
-        #         name: Install Prometheus 
-        #         command: |           
-        #             cd .circleci/ansible
-        #             echo "Contents  of the inventory.txt file is -------"
-        #             cat inventory.txt 
-        #             ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.txt deploy-Prometheus.yml -vv
-                    
-                    
+                            ansible-playbook -i inventory.txt deploy-backend.yml -v              
                     
            - destroy-environment:
                 workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
            - revert-migrations:
                workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
         
-
-            
+    smoke-test:
+        docker:
+        - image: circleci/node:13.8.0
+        steps:
+        - checkout
+        - run:
+            name: Install dependencies
+            command: |
+                sudo apt-get install curl python python-pip && pip install awscli
+        - run:
+            name: Get backend url
+            command: |
+                export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text )
+                export API_URL="http://${BACKEND_IP}:3030"
+                echo "API_URL = ${API_URL}"
+                echo API_URL="http://${BACKEND_IP}:3030" > frontend/.env
+                cat frontend/.env
+                pwd
+        - run:
+            name: Backend smoke test.
+            command: |
+                # Fetch and prepare the BACKEND_IP env var
+                export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text )
+                export API_URL="http://${BACKEND_IP}:3030"
+                echo "${API_URL}"
+                if curl "${API_URL}/api/status" | grep "ok"
+                then
+                    exit 0
+                else
+                    exit 1
+                fi
+        - run:
+            name: Frontend smoke test.
+            command: |
+                URL="https://udapeople-e3d4b36.s3.amazonaws.com/index.html#/employees"            
+                echo ${URL} 
+                if curl -s ${URL} | grep "Welcome"
+                then
+                # Change this to 0 after the job fails
+                exit 0
+                else
+                exit 1
+                fi
+        - destroy-environment:
+            workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+        - revert-migrations:
+            workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+                
                                 
             
     
@@ -347,28 +363,7 @@ jobs:
 
 
 
-#     smoke-test:
-#         docker:
-#             # Lightweight Docker image
-#         steps:
-#             # Checkout code from git
-#             - run:
-#                   name: Install dependencies
-#                   command: |
-#                       # your code here
-#             - run:
-#                   name: Get backend url
-#                   command: |
-#                       # your code here
-#             - run:
-#                   name: Backend smoke test.
-#                   command: |
-#                       # your code here
-#             - run:
-#                   name: Frontend smoke test.
-#                   command: |
-#                       # your code here
-#             # Here's where you will add some code to rollback on failure
+#     
 
 #     cloudfront-update:
 #         docker:
@@ -429,8 +424,8 @@ workflows:
                   requires: [run-migrations]
             - deploy-backend:
                   requires: [run-migrations]
-            # - smoke-test:
-            #       requires: [deploy-backend, deploy-frontend]
+            - smoke-test:
+                  requires: [deploy-backend, deploy-frontend]
             # - cloudfront-update:
             #       requires: [smoke-test]
             # - cleanup:
