Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -390,11 +390,21 @@ jobs:
         - run:
             name: Install dependencies
             command: |
-                sudo apt-get install curl python python-pip && pip install awscli
+                sudo apt update
+                sudo apt upgrade -y
+                sudo apt install -y curl
+                sudo apt-get install python
+                sudo apt-get install python-pip
+                pip install awscli
+                curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
+                sudo apt install nodejs
+                node --version
+                npm --version
+                aws --version
         - run:
             name: Get backend url
             command: |
-                export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text )
+                export BACKEND_URL=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text )
                 export API_URL="http://${BACKEND_IP}:3030"
                 echo "API_URL = ${API_URL}"
                 echo API_URL="http://${BACKEND_IP}:3030" > frontend/.env
@@ -403,14 +413,15 @@ jobs:
         - run:
             name: Backend smoke test
             command: |
-                export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text )
-                export API_URL="http://${BACKEND_IP}:3030"
-                echo "${API_URL}"
+                export BACKEND_URL=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text )
+                export API_URL="http://${backendURL}:3030"
                 if curl "${API_URL}/api/status" | grep "ok"
                 then
-                    exit 0
+                  echo "Backend Smoke Test Success"
+                  exit 0
                 else
-                    exit 1
+                 echo "Backend Smoke Test Failed"
+                 exit  1
                 fi
        
                 # export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text )
